project_id = "jooafkmoizocxgjnfnmg"

[functions.send-handshake-notification]
verify_jwt = false

[functions.check-payment-reminders]
verify_jwt = false


[functions.handle-payfast-itn]
verify_jwt = false

[functions.createPayFastPayment]
verify_jwt = false
