project_id = "jooafkmoizocxgjnfnmg"

[functions.send-handshake-notification]
verify_jwt = false

[functions.check-payment-reminders]
verify_jwt = false


[functions.payfastITN]
verify_jwt = false

[functions.createPayFastPayment]
verify_jwt = false

[functions.repayHandshake]
verify_jwt = false
